### ISSUE TITLE
"make yelmox" seems to not work on v.1801

### ISSUE THREAD

**Issue by JanJereczek** [palma-ice/yelmox#5]
Following the instructions provided in the docs (https://palma-ice.github.io/yelmo-docs/running-with-yelmox/) and running `make yelmox`, an error message is returned:

```
compilation aborted for yelmox.f90 (code 1)
Makefile:91: recipe for target 'yelmox' failed
```

This does not happen while running `make yelmox_ismip6` (fix is probably quite easy?).

**Comment by alex-robinson** [comment]
Thanks! This has been resolved with the tagged version of yelmox `v1.801`.
